@url_users = http://localhost:5000/api/users
@url_posts = http://localhost:5000/api/posts
@random = {{$randomInt 1 100}}
###
GET {{url_users}}
###
POST {{url_users}}
Content-Type: application/json

{
    "name": "User {{random}}",
    "username": "user_{{random}}",
    "address": "address_{{random}}",
    "phone": "+{{$randomInt 1 100}} {{$randomInt 1 10000}} {{$randomInt 1 10000}}"
}
###
DELETE {{url_users}}/3
###
PATCH {{url_users}}/4
Content-Type: application/json

{
    "name": "User {{random}}",
    "username": "user_{{random}}_updated"
}
###
GET {{url_posts}}
###
POST {{url_posts}}
Content-Type: application/json

{
    "user_id": 2,
    "content": "content..."
}
###
GET {{url_posts}}/1
###
PATCH {{url_posts}}/1
Content-Type: application/json

{
    "content": "content... (updated)"
}